### ISSUE TITLE
Proposal for a capability-based security model

### ISSUE THREAD

**Issue by marceline-cramer** [hearth-rs/hearth#104]
Knowledge of Hearth's general design is a necessary prerequisite for understanding this security proposal. To read about Hearth's core philosophy, see [here](https://github.com/hearth-rs/hearth/#philosophy). To read Hearth's design document, see [here](https://github.com/hearth-rs/hearth/blob/main/DESIGN.md).

# Problem

Hearth was originally conceived without the requirement of a security system. All peers on the network are friendly, so why take precautions against malicious attacks? Skipping security would save a lot of development time that could otherwise be spent on adding new features to make Hearth spaces cozier.

Well, no matter how cozy the space, bad days still happen. Personally, I don't know if I would trust *anyone* with unlimited access to my computer's terminal. I have had friends who thought that advertising a script on their web server to play Zelda music in your terminal that would in reality run `sudo rm -rf /*` would make for a good joke. As soon as you apply a non-zero standard of trust to your spacemates then any amount of security begins to seem essential for fear of the worst happening.

So until recently, my solution was to add some "simple" safeguards to host-side systems such as the terminal system to prevent malicious attacks. For example, I designed a `hearth-panels` crate that safely multiplexed keyboard input to different terminal panels on a client's runtime. This ensured that terminal input could only be received from the user's actual keyboard and prohibits other peers from spoofing input. It also provided a host-side channel to terminal input that processes can't listen on, so that sensitive data, such as passwords, never enter guest-side code. If no panel is focused, keyboard input is piped to the "ambient panel", which scripts could subscribe to for keyboard events.

But what if a process detects that the user is about to input a password, so it switches panel focus to the ambient panel without the user noticing, where a service is subscribed to receive the password key input events? This is a trivial attack that immediately and undetectably acquires someone's superuser password. Even if we were to come up with a solution, chances are that there would still exist some backdoor to still gain terminal access that would need to be patched again later. Every time a new patch is made it needs to be redistributed and then every Hearth space needs to restart to adopt the new safeguard.

Solving problems like these is infeasible at scale. Hearth's development team of volunteers doesn't have the time or qualifications to effectively address every single individual security issue that could pop up like this. How many precautions like these are we going to need to take to prevent all possible attacks? Chances are that the "secure" code would eventually grow to dominate the codebase and development of new features would stagnate.

Hearth's philosophy of everything being modifiable at runtime is also at odds with this approach to security. Any time a new vulnerability is found and patched the runtime needs to be restarted. This has a long and inconvenient deployment time and jeopardizes Hearth's stability. However, the addition of a full runtime security model would reinforce Hearth's main goal to make an always-on virtual space.

The best solution is simply to bite the bullet and develop a security system. This would enable us to develop patches at runtime since the permissions of processes can be dynamically updated in response to new vulnerabilities. Although it would cost development time (even just writing this document is costing a lot of time) it would save more time by deprecating any host-side security that would otherwise have been developed. The benefits of designing a security system hugely outweigh the costs, and this document sets out to propose one.

The goal of this GitHub issue thread is to evaluate the following proposal in-depth in an open discussion. I have a good architectural understanding of how this will affect the generalized design of Hearth guest code, but I know little to nothing about formal secure computing theory, so there could absolutely be some major flaws in this idea that I have no way of detecting myself. Any and all help from experienced penetration testers, security specialists, network programmers, malware authors, or general cybersecurity enthusiasts is greatly appreciated! We can't finalize the decision to include this security model in Hearth's design until we can build some consensus from trusted sources as to the effectiveness of this proposal or some future revision of it.

# Premise

If Hearth is to become truly secure, then it must be assumed that no peers can be trusted to accurately represent the behavior of their local processes. Although a local peer may instruct a remote peer to run a known script, that remote peer is still capable of running malicious code in its stead. Consequently, a key security axiom is that any resource access given to any remote process on a peer may be used maliciously by that peer.

Not even the server can be trusted to be benevolent. All peers must be treated equally with regards to granting access to sensitive resources.

For any model to have a trustworthy degree of security, it is essential that remote peers may not gain access to a resource that they are not explicitly granted. To implement this, a local peer may check operations made by a remote peer against a record of granted permissions to assert that invalid permissions are not being used.

Cryptographic authentication and encryption for the purpose of securing peers' policies is unnecessary. Hearth is a client-server architecture, so the server can typically be trusted not to misrepresent peer's behavior to each other. In the rare case of a malicious server, cryptographic authentication would be pointless anyways, because the server would be able to spoof public keys and authenticate fake messages using that. Any dependence on cryptographic authentication would require Hearth's network to diverge from the client-server model. Instead, it would be much simpler to instead ensure that every peer is capable of fending for themselves and independently allowing or denying access to their own private resources. The cryptographic encryption that is used for securing client-to-server network connections is not to be confused with cryptographic permission authentication as it is unrelated to the topic of Hearth's execution security model and instead provides transport-level network security.

# Proposal

The status quo of Hearth permissions is that any process can send messages to any other process by addressing that process with its network-wide ID. The only security lays in the obscurity of process IDs (which is virtually non-existent because every peer can query every other peer's process lists) and in host-side safeguards (which have already been described as ineffective in this document).

I believe that it is the top-down nature of this execution architecture that makes it difficult to secure Hearth. Host-side security is ineffective because it attempts to subtract permissions from the virtually unlimited state space of processes. Safeguard vulnerabilities may almost always be found because processes by default are designed to do anything and access everything.

Instead, an additive process access model may be more productive. Erlang, Hearth's main inspiration, already has this feature. When an Erlang process spawns another process the parent is given an exclusive handle to that new process that no other processes initially have access to. Although the Erlang process handle type is called a "Pid", other processes are not capable of turning integer process identifiers into process handles. The only way to gain access to another process is to be sent a message that contains a handle to that process. All process handles in Erlang originate from the parent of a spawned process or the process itself. 

Note that services are the exception to this rule. Processes in Erlang may be registered under a name, which makes handles to them accessible to any process who looks up that name. Similarly, Hearth's service registry still has merit even under the additive process access model.

If a process was only capable of accessing a certain set of other processes then process access itself could be used as the primary mechanism for security and permissions management. I believe that Hearth should adapt this handle-based approach to process access so that a process security model may be more easily reasoned about.

To demonstrate the effectiveness of handle-based process management, consider that using handles, terminal input events no longer need to be hidden host-side. Only processes that are given a handle to a terminal's control process may send it input events. This allows Hearth to push a huge amount of host-side code guest-side instead, where it may be modified at runtime. In this specific case, new input schemes may also be designed guest-side as a substitute for a physical keyboard. This has a very important application in VR HMD usage where use of a physical keyboard is either limited or unavailable and in-space keyboards are necessary. I believe that this trend will continue for other problem domains like database integration, collaborative editing, and game development, making handle-based process access a very powerful tool to reach Hearth's goals.

However, handles alone do not help peers determine which processes to give sensitive handles to. The runtime has no way of distinguishing between trusted processes that have been loaded by the user for the purpose of accessing the operating system and malicious processes that have been spawned by other peers.

Fortunately, the handle-based process access mechanism paves the way towards a very powerful type of security model: [capability-based security](https://en.wikipedia.org/wiki/Capability-based_security). With capability-based security, the handles themselves are given permission flags that determine which operations processes can perform using that handle. Handles can also be downgraded by processes to new handles with a subset of the original privileges and sent to untrusted processes. Using this system, each runtime can track which processes are trusted and govern access to sensitive resources while still allowing processes to create large systems by distributing safe copies of handles.

Here are some proposed process handle permission flags:
1. `Kill`: the permission to kill this process.
2. `Message`: the permission to send messsages to this process.
3. `Register`: the permission to register this handle as a service on its local peer, thus exposing it publicly to all other processes.
4. `Share`: the permission to send this handle to another peer.
5. `Trusted`: the permission to use this handle on the process's local peer to perform trusted actions, including accessing the operating system outside of Hearth.

These flags are as fine-grained as is reasonable to enable effective use of the [principle of least privilege](https://en.wikipedia.org/wiki/Principle_of_least_privilege). For instance, there are many situations where a process would want to give another process the right to send messages to itself but not to kill it. Fine-grained access control is a major feature of capability-based security and fits well with Hearth's distributed nature.

The premiere feature of including capability-based security and access flags into our process handle model is now that we have a way to flag certain process handles as trusted or untrusted, host-side services can use that trusted status to allow or deny access to the operating system or other sensitive resources. Let's apply this to a real-world design problem: terminal emulator control.

The native terminal emulator spawner process may be registered as a service. This service receives messages that tell it to open new terminal emulator panels on the local peer and to spawn corresponding control processes. Each terminal's control process is used to send input data and other administrative commands to the paired terminal. Although this spawner service is registered publicly while granting full access to the peer's operating system, it can still be made safe using access flags. All the service needs to do is to check the `Trusted` flag of the return handle on the spawn request message as well as the peer ID of the handle. If the handle is both trusted and from the local peer, then the terminal may be opened. Otherwise, the spawner can refuse to open the terminal. Only local, trusted handles should be allowed to access sensitive resources.

How do we know that all local processes with the trusted flag can be trusted? Because we can also configure process spawners to only spawn trusted processes from trusted parents. The WebAssembly process spawner, for example, can check for the peer ID and trusted flag of the return handle in a spawn request. Requests to spawn new trusted processes from an untrusted or remote parent can be denied with an error. Thus, all local, trusted processes **MUST** be spawned from other local, trusted processes. It's impossible for remote peers to escalate privileges because all local processes must be spawned from spawner services that check for this flag to be set.

All guest code should be written defensively and only send handles to other processes with the minimal permissions necessary for the given context. This defensive mindset will be essential in making large-scale, secure systems in Hearth, because while capability-based security provides a good general security model, it is not a magic bullet against security vulnerabilities. The benefits of it are that fixes to vulnerabilities can be updated at runtime and that it provides a good mental model for building safe architectures.

I believe that this handle-based access model based on permissions gives us all of the tools necessary to build complete, secure, modular distributed systems in Hearth. Handles limit which processes have access to which other processes. Permission flags on each handle are unforgeable signifiers of authority. The distribution of privileges to remote peers can be tracked locally, and authoritative actions by remote peers can be safely granted or denied. In conjunction, these design aspects provide essential tooling to safely build spaces in collaboration with less-than-trusted peers.

# Design Details

When a process is spawned, it receives a "self handle", which is naturally a handle to itself. This handle is the only handle processes possess to begin with. It can be copied and sent to other processes to be used as a "return address" for messages, or to perform operations such as sending messages to itself or killing itself.

The same logic that applies to handles with the `Trust` flag applies to other permission flags like `Register` and `Share`. Non-`Register` handles cannot be used to spawn `Register` processes. Non-`Share` handles cannot be used to spawn `Share` processes. This ensures that processes cannot escalate the permissions granted to them using their self handle or sent to them by other peers.

Message protocols featuring request-response formats will often bundle handles in the request message pointing to the sender of the request. This can be used by the receiving process as the handle to send the response message back to. This is similar in function to a return address on a letter.

Importantly, return address handles do not need to be handles to the process sending the request. This means that a process may make a request to a service but instruct the service to send the response to a different process instead of itself. The consequences of this are not fully understood and should be discussed while ratifying this proposal document.

Trusted processes will need to be loaded externally since no processes already running can escalate privileges to become trusted. Therefore, the runtime should provide some user-facing mechanism to load new trusted processes into the local peer. Some examples of processes that would be loaded with this method are local UI scripts, panel and terminal managers, server-authoritative scripts, or local file storage.

Global process IDs are still useful for distinguishing processes from each other for both running processes and users. There will be a mechanism for guest processes to get the process ID of any handle. This can be used for testing equality of handles, logging debug messages, or sorting handles by process. Process IDs are also convenient for users to reason about human-readable IDs of each process and retrieve metadata like resource usage or logs.

# Discussion

The number one question that we need to answer about this security model is: will this be condusive towards creating fully secure distributed systems, and can we trust this to defend users' computers from malicious attacks? This will require some thought experimentation and research to answer, so please share any thoughts in a comment.

Outside of that question, here are some other important things to discuss about this security model:

- Should we log warning messages when handles with the `Trusted` flag are sent to remote peers? Should we disallow that altogether? Or should we just ignore it? What are the potential applications of sending `Trusted` handles to remote peers? Does allowing it make accidental vulnerabilities easier to write?
- Should we support custom permission flags? We provide a set of base flags for basic process operations and rely on access to specific processes for fine-grained security. Is this sufficient, or should processes also be allowed to create, distribute, and check handles with custom permissions flags? This would require a lot of work to add support to the protocol and scripting API.

After ratifying this proposed security model with third parties, we can progress towards implementing this in Hearth. This is going to be a major overhaul, affecting documentation, core runtime design, the network protocol, and IPC applications. We can figure out what specifically needs to get done based on the conclusions we come to about this model in this thread.

# Resolved

- It should be possible for peers to revoke other peers' handles.
- It does not matter that processes can give another process's handle as a return address in a message because that process could have forwarded a response to that process using the `Message` permission anyways.
- We cannot and should not prevent processes from copying and sending handles to other processes, because capability-based security benefits from and assumes capability-copying as a feature.

**Comment by technobaboo** [comment]
There's another HUGE problem that I feel was left out: how to make sure the user does not get permission fatigue and is able to act on all these permissions.

Permission fatigue is a much bigger problem than most people realize, cookie banners work so well because people give up, and even with a trustworthy platform people will inevitably find bugs, then enable all the permissions to try to get it to work.

And even if you can avoid fatigue, this permissions model seems to be very abstract, tangibility is something that's needed for things to be intuitive and this requires a mapping to something tangible. Even if you assume only people who have lots of technical experience are using this, they will have bad days where thinking is hard!

This is why in Stardust, there's no capabilities or permissions at all! Security and privacy are maintained by separation of concerns in a way that is consistent and intuitive. Objects can get aliases of other objects (kinda like handles, but on a much more precise level), but those only work for specific actions related to how the alias was acquired. For example, zones can manipulate other objects spatially but they have zero clue about anything other than the size of the spatial and its transform, there's no metadata. When an item is captured into an item acceptor, the acceptor can do anything it wants to that item! but the item's UI determines when it's put into an acceptor and is assumed trustworthy. This model means that for a person trying to use the system, they do not ever need to worry about a permission dialog, they can just look at the object and instantly tell what has access to what and can just... yank it out if they don't like it.

I'm sure capabilities can work, but I personally would like this security and privacy model to be _better_ than anything before, and making your technical implementation inherently work well for people without heavy abstractions on top is a key step. So at least be aware of the problems, but I think a fundamentally different model would take this project to the next level.

**Comment by makoConstruct** [comment]
> use of a physical keyboard is either limited or unavailable and in-space keyboards are necessary. I believe that this trend will continue for other problem domains like database integration, collaborative editing, and game development, making handle-based process access a very powerful tool to reach Hearth's goals.

I don't believe limited physical keyboard access will continue, the ML problem of recognizing a keyboard (any keyboard) and clearing an AR cutout for it, is not substantially harder, and probably far easier than the problem of tracking hands. More likely, we'll get a generalized version of this for any object on top of a desk, like [this](https://twitter.com/AlphaSignalAI/status/1643637715571732483).

Virtual controls will probably continue to be a thing though?

> Is support for revocation of handles necessary? If a malicious process is accidentally granted access to a handle that it shouldn't possess, is there a way to forcefully remove access?

It's crucial. You might also want to rate-limit a lot of operations, or wire them to report to someone if they're used too much.

> What are the consequences of allowing processes to include any handle in the return addresses of request messages?

Nothing, as the requester could have always taken the return address and then sent it on to someone else, as a second step. This allows them to not do that, which might be useful for for processes that want to give another process the ability to do something while kinda proving that they themselves didn't get a copy of that ability, for instance, creating a private space for someone else, which they know you wont be able to snoop into.

> Can we make a flag to allow or disallow the copying of handles?

Capability principles would tend to say no, because an actor can always make a process of their own that behaves as a proxy for a handle, which is functionally equivalent to copying it, but potentially sketchier. Similar things can be said of `Register` and `Share`. I wouldn't need permission to register your process if I have a handle that to it, I can just register a new process of my own, and broadcast that it reflects the special process.

**Comment by lilithium-hydride** [comment]
So an untrusted process is unable to launch trusted processes. That's a logical step in the right direction, but it doesn't solve privilege escalation. Trusted processes will very likely end up communicating with untrusted processes and working with data originating from them. WebAssembly, despite what the homepage claims, [does not innately defeat control-flow modification exploits](https://arxiv.org/abs/2111.01421), and very dangerous, memory-unsafe code *will* end up running as trusted . Any trusted process that must by its nature accept communications from a large subset of the network makes for a very appealing target, as anything that can modify its control flow is able to pwn the machine it's running on. I don't have a great solution to this, unfortunately.

**Comment by marceline-cramer** [comment]
> And even if you can avoid fatigue, this permissions model seems to be very abstract, tangibility is something that's needed for things to be intuitive and this requires a mapping to something tangible. Even if you assume only people who have lots of technical experience are using this, they will have bad days where thinking is hard!

@technobaboo: I think you may be misunderstanding the point of the Hearth security model. We're not working to define Android-style app permissions UX, we're trying to find a very low-level permissions system so that autonomous processes can't escalate their permissions without the users' trust. This has more in common with POSIX security definitions than with something like Android, although even POSIX security is often directly interacted with by users via groups and file permissions. UX must still be a consideration at some point, but it's not very relevant at this low of a level. We're trusting that capability-based security systems make for good-enough UX after designing them, because they historically have.

> This requires the user to either blindly trust software (because they're just not gonna have the time to check tbh), or to trust someone that trusts that software and may not have verified it. That'll just cause the rm -rf /* prank again when a friend says "hey i made this cool script for your terminal" or such.

There's nothing we can do about this. My intent with bringing up the `sudo rm -rf /*` prank wasn't to suggest that anyone would make this exact attack, my point was that if there were any naive trust assumptions in Hearth, it would be trivial for those kinds of people to make attacks on other users' spaces. Outside of the spawning of processes and message-passing that occurs in the runtime, Hearth has no authority of policy of general safe computer usage.

> I'm sure capabilities can work, but I personally would like this security and privacy model to be _better_ than anything before, and making your technical implementation inherently work well for people without heavy abstractions on top is a key step. So at least be aware of the problems, but I think a fundamentally different model would take this project to the next level.

It would be productive to consider other models too, but only if this specific model doesn't have any critical security vulnerabilities, which take priority over soft UX requirements. Proposing another security model would require consideration of Hearth's specific functionalities, a whole new proposal design document, and a long-term auditing stage like with this one. If you have the time for that though, I'd love to hear what you had in mind.

> I just realized this might also help a lot with ensuring security too, because with separation of concerns you can just test each system individually, and then if an exploit is found between multiple systems you can patch the component systems... with permission flags you have to then convey that to the user of what's dangerous or possibly break things more often.

This is a really great topic to bring up. I'm sure that a serious Hearth security test framework would include some critical trusted Wasm processes that are spun up on a sandboxed Hearth runtime and then tested for vulnerabilities by scripted processes. This is really combining the best of both Erlang concurrent programming, object-oriented clean code, and capability-based security.

**Comment by airidaceae** [comment]
> WebAssembly, despite what the homepage claims, [does not innately defeat control-flow modification exploits](https://arxiv.org/abs/2111.01421), and very dangerous, memory-unsafe code will end up running as trusted

@lilithium-hydride I think that this is somewhat besides the point. Somewhere between most and all scripts we write for the core systems and plugins of Hearth will be made in Rust and so they should be memory safe by default. In the case that we do need to write in C or another language, it is up to us to be very careful and avoid vulnerabilities like the good little code kitties we are. A message will not contain code for a trusted process to just blindly run. Granted, some code will still have issues and vulnerabilities but those should be vulnerabilities that we can patch out in the same way any vulnerabilities in a traditional, single-threaded software application would be handled. The purpose of the security model is to give us a strong foundation to build secure systems on.

In the case that someone does write a script in C that is memory unsafe, that's mostly on them but there are ways to handle it. Wasmtime, the WebAssembly interpreter that we are running throws something called a trap when a memory violation occurs. In this case we will adopt the same method of error handling that Erlang does and instantly exit any failing processes, because more processes can be easily spun up.

While malicious code injection is something we are scared of, this model handles it pretty well. If I were to spawn a process that is intentionally vulnerable so I could abuse it, I can't gain anything from that. The most that process can give me is the permissions I had already spawned it with. Granted this could be used for persistence which is something that is mildly concerning to me but at that point there are probably many ways that someone could make persistence that would even be considered intended features. Revoking permissions is complicated and its probably best to kill all processes spawned by someone in the time-frame of them gaining a permission to them losing that permission.

**Comment by technobaboo** [comment]
@marceline-cramer my point is that the capability-based model's UX is not good enough! If it was, then we wouldn't have cookie banners and permission dialogs on every app install and so on causing a large portion of people to just give away permissions. To make good UX you have to make the low level based on the UX just as the UX has to be based on the low level.

**Comment by lilithium-hydride** [comment]
@airidaceae I already talked to you about most of this privately, but I'm responding again here for the benefit of the public discussion. 

> Somewhere between most and all scripts we write for the core systems and plugins of Hearth will be made in Rust and so they should be memory safe by default. In the case that we do need to write in C or another language, it is up to us to be very careful and avoid vulnerabilities like the good little code kitties we are.
 
I don't doubt that the vast majority of 1st-party Hearth code will be written in safe Rust. However, this still leaves me with two concerns. One is simply that Hearth's very design and goals mean that people will *not* be purely running hyper-secure, continually-audited, safe Rust code as `trusted`. I would certainly hope that the barrier to entry for community Hearth development is not so high that your average nerd couldn't write and distribute popular scripts, but this hypothetical Average Nerd is not necessarily programming with their tinfoil hat on and could put people in a very risky situation if other systems are not in place to reduce the impact of their unsecure code. After all, if all code could be treated as angelically pure and safer than Fort Knox, we wouldn't need to be discussing security right now. I'm not suggesting that it's possible, feasible, or even desirable to tighten things enough that it's impossible to mess up, only that we should not be operating under any false assumptions here. My other concern is that, unless I'm missing something (and I admit that I may be, @marceline-cramer feel free to correct me here), your Rust scripts must still incorporate unsafe code which comes into contact with raw bytes, FFI shenanigans, etc., and you're still left responsible for manually processing that data in a safe manner before passing it along to the safe areas of the script. 

> A message will not contain code for a trusted process to just blindly run.

It *shouldn't*. Under normal circumstances, it won't. However, we cannot treat that as a guarantee. Shellcode is real and it's coming for you.

> Wasmtime, the WebAssembly interpreter that we are running throws something called a trap when a memory violation occurs.

If this works anything like a stack canary, talk to the gcc devs about why this approach isn't as solid as one may think. Again, I'm not enough of a wasmer to say how effective of a countermeasure this is.

> If I were to spawn a process that is intentionally vulnerable so I could abuse it, I can't gain anything from that. The most that process can give me is the permissions I had already spawned it with.

Yes, but again, I'm mostly talking about trusted processes here, because they're the juiciest targets. It's also worth mentioning that taking over an untrusted process may still be beneficial for [pivoting](https://csrc.nist.gov/glossary/term/pivot) into a partially isolated trusted process. 

> there are probably many ways that someone could make persistence that would even be considered intended features.

I'm sure that somebody could do something interesting with this, yes. However, this seems to contradict your assumption that you won't be able to just send commands (code or otherwise) to processes. What goal does establishing persistence on somebody's system have if not to facilitate your future interacting with that process? 


I hope none of this comes off the wrong way (and that it was generally intelligible), I'm just trying to make sure that everybody is able to see the full picture, in all its vastness and minutiae, when it comes to the security of the 56 billion devices running ~~Java~~ Hearth and of the ecosystem in general.

**Comment by lilithium-hydride** [comment]
@technobaboo 
> my point is that the capability-based model's UX is not good enough! If it was, then we wouldn't have cookie banners and permission dialogs on every app install and so on causing a large portion of people to just give away permissions. 

This doesn't feel like a very coherent argument. Cookie banners are an intentionally user-hostile system created in response to the GDPR and are designed specifically to wear users out until they begin just clicking whichever button makes it take up the least amount of space on the page. App permission dialogs are an OS feature that makes an earnest attempt at exposing a user-friendly interface to the underlying permissions API. The two are vastly different in purpose, function, and implementation, with the only similarity being in the effect that the constant popups have on some people. This is, as you admit, entirely a UX issue, which exists at a much higher level than the underlying low-level security features that are the subject of this issue.

> To make good UX you have to make the low level based on the UX just as the UX has to be based on the low level.

This is simply not the case, and a look at Android's many security mechanisms (it's all out there in the open) proves this. The UX discussion is not a productive one to have right now, and is off-topic as far as this purely security-focused discussion goes.

**Comment by marceline-cramer** [comment]
@makoConstruct 

> > use of a physical keyboard is either limited or unavailable and in-space keyboards are necessary. I believe that this trend will continue for other problem domains like database integration, collaborative editing, and game development, making handle-based process access a very powerful tool to reach Hearth's goals.
> 
> I don't believe limited physical keyboard access will continue, the ML problem of recognizing a keyboard (any keyboard) and clearing an AR cutout for it, is not substantially harder, and probably far easier than the problem of tracking hands. More likely, we'll get a generalized version of this for any object on top of a desk, like [this](https://twitter.com/AlphaSignalAI/status/1643637715571732483).
> 
> Virtual controls will probably continue to be a thing though?

Yeah! Virtual controls, AR or not, are still a big deal, and with a security model we'd have more flexibility in how we can approach support and handling of those integrations into Hearth.

> > Is support for revocation of handles necessary? If a malicious process is accidentally granted access to a handle that it shouldn't possess, is there a way to forcefully remove access?
> 
> It's crucial. You might also want to rate-limit a lot of operations, or wire them to report to someone if they're used too much.

Good to know, let's factor support for revocation and rate-limiting into our designs.

> > What are the consequences of allowing processes to include any handle in the return addresses of request messages?
> 
> Nothing, as the requester could have always taken the return address and then sent it on to someone else, as a second step. This allows them to not do that, which might be useful for for processes that want to give another process the ability to do something while kinda proving that they themselves didn't get a copy of that ability, for instance, creating a private space for someone else, which they know you wont be able to snoop into.

This is a really powerful insight into the logic of capability systems; good catch.

> > Can we make a flag to allow or disallow the copying of handles?
> 
> Capability principles would tend to say no, because an actor can always make a process of their own that behaves as a proxy for a handle, which is functionally equivalent to copying it, but potentially sketchier. Similar things can be said of `Register` and `Share`. I wouldn't need permission to register your process if I have a handle that to it, I can just register a new process of my own, and broadcast that it reflects the special process.

This is another really valuable insight, good to know.

Sweet, this all helps in reducing down our problem space of how to implement a capability system. Thank you for the input!

**Comment by marceline-cramer** [comment]
@lilithium-hydride 

No, we can't expect all the trusted code to run in Hearth to be perfectly secure. However, there will still be a degree of separation between trusted processes and processes that interact with trusted processes but are not trusted. For example, we might provide a super low-level protocol to talk to a trusted, host-side process that provides a terminal, database, filesystem, or whatever. Then, we (the Hearth team) would implement a guest-side process to talk to that process and provide a mid-level API to processes. That guest-side process would be security-sensitive, because untrusted processes could interact with it.

The greatest advantage to this security model is that that mid-level, security-sensitive code is running as a guest and not in the host. This way, when we do inevitably find security loopholes in our secure code, we can quickly patch and deploy fixes onto running Hearth instances. Without the distinction between trusted and untrusted processes, security-sensitive code would have to run host-side instead, which is much harder to work with. There's not really any getting around the need for untrusted code to have some degree of indirect access to trusted systems, because even if we weren't providing access to user's shells, server-side databases and other sensitive data would still need to be secured.

In either case, most Hearth development will be on untrusted code that works on those mid-level abstractions, both for the core team and for casual users. We don't expect users or developers to generally have to pay close attention to what is and is not trusted, unless they are extending the features of that mid-level guest code.

This is kind of comparable to the Linux ecosystem. Every Linux user runs a highly trusted kernel and set of device drivers, but 99.9% of code that is modified and loaded onto Linux runs in userspace. Similarly, Hearth will have its own team of developers that work on host-side code (the kernel) and trusted guest-side code (the drivers) which is highly scrutinized for security, while almost everyone else works on untrusted code that can be run safely without many security considerations.

Re FFI: Yeah, Hearth's guest-side FFI is unsafe, but that code is and will always stay as tiny and simple as possible, and auditing that should be as simple as just reading the code to know for certain that no, exploits of that boundary are not possible. We'll of course make sure that FFI is scrutinized for security vulnerabilities, but all that FFI needs to provide is a handful of host functions to perform fundamental operations like sending messages. [Here's the current guest-side FFI code.](https://github.com/hearth-rs/hearth/blob/main/crates/hearth-guest/src/lib.rs)

**Comment by marceline-cramer** [comment]
Closing for now since the discussion is dead. Feel free to reopen to address any loose ends.
