### ISSUE TITLE
Service naming conventions

### ISSUE THREAD

**Issue by marceline-cramer** [hearth-rs/hearth#142]
Needed for #130. Also needs follow-up code modifications to ensure that all of our native services follow the conventions we decide upon.

I think the general idea is that we could use Java-style "canonical names" such as `rs.hearth.wasm.WasmSpawner`.

@lilithium-hydride do you have any info on how canonical names are created not just in Java but in other places like D-Bus?

**Comment by lilithium-hydride** [comment]
My understanding of Java's canonical names is basically this (which, from a cursory glance at https://docs.oracle.com/javase/tutorial/java/package/namingpkgs.html, appears to be correct):
```
tld.domain<.subdomain>  .  projectname     <.classname>
        ↑                      ↑               ↑
 website associated       name of the      the class or
 with the project,        actual project   some other sub-
 or maybe a github       (kindling, etc.)  object
 user like:
 com.github.hearth_rs
 (note the replacement
 of the hyphen)
```
Further sub-objects are tacked on as expected. This isn't just some abstract name, however. For the example you provided, you'd expect to see a directory structure like the following:
```
rs
 └ hearth
    └ cognito
       └ WasmSpawner.java
```
Of course, you can stray as far from Java's questionable specifications as you want, taking from it only what you need. It's great if you're really aiming for that Enterprise Experience™, though.

As for D-Bus, I'll spare you the rant and just link to https://dbus.freedesktop.org/doc/dbus-api-design.html. Naming conventions are discussed in a few places. If you want to see how things actually pan out, I'd recommend installing a D-Bus explorer and poking around for a bit. It's not pretty.

**Comment by marceline-cramer** [comment]
I don't think we'll ever need anything past just:
```
<author/org>.PascalCaseServiceName
```

so:
```
hearth.Filesystem
hearth.Audio
hearth.Window
kindling.Physics
kindling.WindowManager
```

In kindling's case, we're using the name "kindling" as an identifier for the different service protocols and a link to what defines those protocols the best, even if the user isn't necessarily using kindling as their init system.

**Comment by airidaceae** [comment]
Is this solved?

**Comment by marceline-cramer** [comment]
> Is this solved?

are we ok to sign off on the `something.Service` standard @siltyy @airidaceae?

**Comment by lilithium-hydride** [comment]
Yeah, I think this is fine. 

Nov 19, 2023, 11:56 by ***@***.***:

**Comment by BurningEmbyr** [comment]
I think there has to be a standard for author and project names, too - and for which one is used. If you have authors like Google (one word, first letter capital), IKEA (one word, all capital), and Best Buy (two words, title case, space), there's room for inconsistency - Is it IKEA.Window, ikea.window, BestBuy.Renderer, Best_Buy.Renderer, bestBuy.Renderer, bestbuy.Renderer? Do we want hearth, with the lowercase project name, to set the standard for how projects should be capitalized? I would advise yes - otherwise you have a mish-mash of things like
```
hearth.WindowManager
WILDFIRE.TreeComponents
JamieSmithsCoolProject.ThisReallyCoolThingIDid
```
I'd advise we stay away from Java's way of doing things - it pre-supposes a domain, and I don't like that on a personal level.[^1]

My proposal would be:
```
<all lowercase project name>.PascalCaseServiceName
```
with spaces in the project name removed.

[^1]: Don't get me wrong I love domains but expecting devs to have one and use it for a project feels off to me
