### ISSUE TITLE
runtime: instrument `ProcessRunner` with tracing subscriber that redirects to process log

### ISSUE THREAD

**Issue by marceline-cramer** [hearth-rs/hearth#209]
We'd like to have interoperable tracing events and process log events that can be distributed through Hearth's upcoming debug API, so let's instrument the `run` functions of `ProcessRunner` implementations with a custom tracing subscriber that can output tracing events to that runner's process's log.

We'll need to add a provided `ProcessRunner::spawn` function that calls `tokio::spawn` with a `ProcessRunner::run` future that is instrumented using [this](https://docs.rs/tracing-futures/latest/tracing_futures/) and a tracing subscriber that uses the process's `log_tx` field to log events. Then, in `ProcessFactory::spawn_with_table`, we'll want to receive the process log events and re-emit all process logs as NEW tracing events with the default stderr-based tracing subscriber, perhaps incorporating metadata about the logging process such as the name or PID. Let's try to incorporate into tracing's API the best we can, by routing the process log's level, target, description, etc. to the tracing events, instead of simply debug formatting `ProcessLogEvent` like we are at the current moment. Finally, we'll need to replace all instances in the codebase of manually spawning `ProcessRunner::run` tasks by calling `ProcessRunner::spawn` to automatically instrument them.

Please let me know if you have any questions! I know that this is a pretty complex task that touches a lot of code, but I know that you can do it. :)

**Comment by ten3roberts** [comment]
There is currently a slight issue regarding re-emitting tracing events, as they have to be constructed statically.

This prevents using dynamic or at-runtime fields and targets to construct a metadata. This means that the re-emitted events won't have the callsite of their original event, but the callsite inside `spawn_with_table`.

This is unfortunate.

https://github.com/tokio-rs/tracing/issues/2730

Let me know if I should open a new issue for it, rather than replying to an older one.

Something else we can do is invert the issue, and instead remove the `log_tx` entirely, and use the global subscriber directly for native plugins.

For kindlings (I do believe that is the right name for our wasm modules), we could instead make the `log` export construct a tracing event right there and then to invoke the global subscriber directly.

If we would like the process log stream to function as a UI, such as presenting the logs in-world as a widget instead of in the external terminal, we could write a custom global subscriber that catches tracing events and emits them as these UI events.

That way, there will not be this inconsistent disparity between `debug!` inside a native process, and inside another async function or a spawned task from within a process.

I feel that the initially proposed solution may lead to this odd "two pathways" behavior, where the logs may go one way or another depending on an external out of control factor, and would thus prefer if we treated all logs equally and did it this other way around.

With all this said, it is *your* code, and I am as of now just an external consultant (with a high fee of $0/hour), hehe, so I dutifully respect your opinion as to which direction to pursue.

**Comment by ten3roberts** [comment]
In regards to separating log messages based on their origin process, this would still be naturally achievable by using [`spans`](https://docs.rs/tracing/latest/tracing/span/index.html), which would allow the subscriber which redirect to the in-world UI or hearth-ctl to separate and group them by process, with the added benefit of even greater nuance, such as which process spawned which etc.

What is intended functionality of the hearth-ctl functionality described by https://github.com/hearth-rs/hearth/issues/75#issue-1624236139? Would it be to receive all the `log_rx` events and print them to the controlling terminals stdout, or something else?
